/**
 * container-admin.ts — container_admin（v1.30：机务舱——容器管理面统一入口）
 *
 * 合并自：
 *   · skiff_admin（F4 Skiff 认知子集角色：guide/validate/apply/list）
 *   · acc_msm 管理面（register/deregister/check/guide/catalog/ccc-config）
 *     —— msm 工具只管执行+发现；一切「管理容器」的操作归本工具
 *
 * 语义（用户拍板"skiff_admin 及系列 admin 合并成 container_admin"）：
 *   container = CCC（具体认知容器）；admin = 管理操作。
 *   类比 The Manifest（清单维护——工具注册表）+ Crew（角色管理）+ 机务（配置/手册）。
 *
 * 参数极简（LLM 直觉）：domain（管理域）+ action（该域子命令）+ 少量业务参数。
 */

import { defineTool } from '@deepseek-ai/dsh-tools'
import type { ContentBlock } from '@deepseek-ai/dsh-llm'
import type { JsonValue } from '../json.js'
import { findSerenityRoot } from '../ccc.js'
import { runMsm, MSM_ACTIONS } from '../msm-ops.js'
import { skiffMsmGate } from '../skiff-core.js'
import { validateSkiffConfig, applySkiffConfig, listSkiffRoles, SKIFF_GUIDE } from './skiff-admin.js'

function agentCwd(exec: { agent?: { session?: { header?: { cwd?: string } } } }): string {
  return exec.agent?.session?.header?.cwd ?? process.cwd()
}

function agentSessionId(exec: { agent?: { session?: { id?: string } } }): string {
  return exec.agent?.session?.id ?? ''
}

function renderText(value: unknown): ContentBlock[] {
  const text = typeof value === 'string' ? value : JSON.stringify(value, null, 2)
  return [{ type: 'text', text }]
}

/** 管理域（container_admin 一级参数） */
export type AdminDomain = 'role' | 'msm' | 'config'

const DOMAIN_INTRO: Record<AdminDomain, string> = {
  role: 'Skiff cognitive-subset roles: guide (tutorial) / validate (config check) / apply (validate + confirm live) / list (role summary)',
  msm: 'MSM registry management: register / deregister / check (DC-M1~M4 quality) / guide (dev manual) / catalog (ACC capability directory) / ccc-config (CCC config reference)',
  config: 'CCC configuration (read-only view of .opencode/serenity.json sections) — direct edits go through filesystem',
}

/** 管理面动作映射：domain → 可执行 action（转发到底层 runMsm / skiff 逻辑） */
const ADMIN_ACTIONS: Record<AdminDomain, readonly string[]> = {
  role: ['guide', 'validate', 'apply', 'list'],
  msm: ['register', 'deregister', 'check', 'guide', 'catalog', 'ccc-config'],
  config: ['view'],
}

export const containerAdminTool = defineTool({
  name: 'container_admin',
  description:
    'Container administration (the ship\'s maintenance bay — one entry for managing the CCC): ' +
    'role — Skiff cognitive-subset roles (guide/validate/apply/list); ' +
    'msm — MSM registry management (register/deregister/check quality DC-M1~M4) + manuals (guide dev manual / catalog ACC capability directory / ccc-config CCC configuration reference); ' +
    'config — view CCC configuration. Execution of registered MSMs belongs to the msm tool; this tool manages the container.',
  parameters: {
    domain: {
      type: 'string',
      enum: ['role', 'msm', 'config'],
      required: true,
      description: 'Management domain: role (Skiff roles) / msm (MSM registry + manuals) / config (CCC config view)',
    },
    action: {
      type: 'string',
      description: 'Domain subcommand (see domain descriptions; e.g. role: validate/apply/list/guide; msm: register/deregister/check/guide/catalog/ccc-config)',
    },
    // register 参数（msm 域）
    name: { type: 'string', description: 'MSM name (register/deregister)' },
    path: { type: 'string', description: 'register: script relative path inside root' },
    category: { type: 'string', description: 'register: mech | semi-mech' },
    description: { type: 'string', description: 'register: one-line description' },
    skill: { type: 'string', description: 'register: owning skill' },
    flags: { type: 'string', description: 'register: flags JSON string (e.g. [{"name":"x","type":"string"}] — type:"path" enables escape guard)' },
    usage: { type: 'string', description: 'register: custom usage (auto-generated by default)' },
  },
  output: {
    schema: { type: 'json' },
    render: (args, value) => renderText(value),
  },
  async execute(args, exec): Promise<JsonValue> {
    const root = findSerenityRoot(agentCwd(exec))
    if (!root) throw new Error('No CCC found: no .serenity file from agent cwd')
    const sessionId = agentSessionId(exec)
    const domain = args.domain as AdminDomain
    const action = (args.action as string | undefined) ?? ''

    // Skiff 会话安全：role apply/validate 只读放行；msm register/deregister 必拒
    if (domain === 'msm' && (action === 'register' || action === 'deregister')) {
      const gate = skiffMsmGate(root, sessionId, action, args.name as string | undefined)
      if (gate.reject) throw new Error(gate.reject)
    }

    // role 域 → skiff 逻辑（原 skiff_admin 子命令）
    if (domain === 'role') {
      switch (action) {
        case 'guide': return { guide: SKIFF_GUIDE }
        case 'validate': return validateSkiffConfig(root)
        case 'apply': return applySkiffConfig(root)
        case 'list': return listSkiffRoles(root)
        default: throw new Error(`container_admin role requires action: guide | validate | apply | list`)
      }
    }

    // msm 域 → 原 acc_msm 管理 action（exec 不在此——exec 走 msm 工具）
    if (domain === 'msm') {
      const mgmtActions: string[] = ['register', 'deregister', 'check', 'guide', 'catalog', 'ccc-config']
      if (!mgmtActions.includes(action)) {
        throw new Error(`container_admin msm requires action: ${mgmtActions.join(' | ')} (execution goes through the msm tool)`)
      }
      // 同步执行（register/deregister 走 git 精提交；check/guide/catalog/ccc-config 纯读）
      const out = runMsm(root, {
        action: action as (typeof MSM_ACTIONS)[number],
        name: args.name as string | undefined,
        skill: args.skill as string | undefined,
        path: args.path as string | undefined,
        category: args.category as string | undefined,
        description: args.description as string | undefined,
        flags: args.flags as string | undefined,
        usage: args.usage as string | undefined,
      })
      return out
    }

    // config 域 → CCC 配置总览（ccc-config 引用；直接视图）
    if (domain === 'config') {
      const ref = runMsm(root, { action: 'ccc-config' })
      return { config: ref }
    }

    throw new Error(`container_admin requires domain: role | msm | config`)
  },
})
