/**
 * msm.ts — acc_msm 真实 DSH 工具定义（defineTool）
 */

import { defineTool } from '@deepseek-ai/dsh-tools'
import type { ContentBlock } from '@deepseek-ai/dsh-llm'
import { findSerenityRoot } from '../ccc.js'
import { runMsmAsync, MSM_ACTIONS } from '../msm-ops.js'

function agentCwd(exec: { agent?: { session?: { header?: { cwd?: string } } } }): string {
  return exec.agent?.session?.header?.cwd ?? process.cwd()
}

function renderText(value: unknown): ContentBlock[] {
  const text = typeof value === 'string' ? value : JSON.stringify(value, null, 2)
  return [{ type: 'text', text }]
}

export const msmTool = defineTool({
  name: 'acc_msm',
  description:
    'MSM (Mech & Semi-Mech) framework: list lists registered MSMs (header+flags display); exec executes (600s timeout, path-escape + symlink blocking, injects SERENITY_ROOT/CCC/VERSION env, appends --help TIP on failure; first arg --list/--schema/--format=json is protocol); register/deregister manage the registry (path inside root + script exists + globally unique validation, auto git precision commit); check quality checks DC-M1~M4; guide development manual; ccc-config CCC config reference (handyman.models/sessionKeeper.threshold/localstore.gitTrack/hooks.autoRestoreSession). Reuses the CCC mech-registry.json.',
  parameters: {
    action: { type: 'string', enum: [...MSM_ACTIONS], required: true, description: 'Subcommand: list/exec/register/deregister/check/guide/ccc-config' },
    name: { type: 'string', description: 'MSM name (exec/register/deregister)' },
    args: { type: 'array', items: { type: 'string' }, description: 'exec business args (first arg --list/--schema <n>/--format=json is protocol flag, rest passed through losslessly)' },
    skill: { type: 'string', description: 'register owning skill' },
    path: { type: 'string', description: 'register script relative path (must be inside root and exist)' },
    category: { type: 'string', description: 'register category (mech/semi-mech)' },
    description: { type: 'string', description: 'register description' },
    flags: { type: 'string', description: 'register flags JSON string (new-style object array; type:"path" enables escape validation)' },
    usage: { type: 'string', description: 'register custom usage (auto-generated by default)' },
  },
  output: {
    schema: { type: 'json' },
    render: (args, value) => renderText(value),
  },
  async execute(args, exec) {
    const root = findSerenityRoot(agentCwd(exec))
    if (!root) throw new Error('No CCC found: no .serenity file from agent cwd')
    // runMsmAsync：exec 用异步 execFile（不阻塞 web 事件循环，避免 MSM 自请求 3080 死锁）
    return runMsmAsync(root, args)
  },
})
