/**
 * msm.ts — acc_msm 真实 DSH 工具定义（defineTool）
 */

import { defineTool } from '@deepseek-ai/dsh-tools'
import type { ContentBlock } from '@deepseek-ai/dsh-llm'
import { findSerenityRoot } from '../ccc.js'
import { runMsmAsync, runMsm, MSM_ACTIONS } from '../msm-ops.js'
import { skiffMsmGate } from '../skiff-core.js'

function agentCwd(exec: { agent?: { session?: { header?: { cwd?: string } } } }): string {
  return exec.agent?.session?.header?.cwd ?? process.cwd()
}

function agentSessionId(exec: { agent?: { session?: { id?: string } } }): string {
  return exec.agent?.session?.id ?? ''
}

function renderText(value: unknown): ContentBlock[] {
  const text = typeof value === 'string' ? value : JSON.stringify(value, null, 2)
  return [{ type: 'text', text }]
}

export const msmTool = defineTool({
  name: 'acc_msm',
  description:
    'MSM (Mech & Semi-Mech) framework: list lists registered MSMs (header+flags display); exec executes (600s timeout, path-escape + symlink blocking, injects SERENITY_ROOT/CCC/VERSION env, appends --help TIP on failure; first arg --list/--schema/--format=json is protocol); register/deregister manage the registry (path inside root + script exists + globally unique validation, auto git precision commit); check quality checks DC-M1~M4; guide development manual; catalog ACC usage directory (all capability areas — points to each feature guide, single source of truth); ccc-config CCC config reference (all sections: handyman.models / sessionKeeper.threshold / localstore.gitTrack / hooks.autoRestoreSession / safeMode.blacklist / skiff.roles / autopilotTrajectory / weixin incl. message hook full guide). Reuses the CCC mech-registry.json.',
  parameters: {
    action: { type: 'string', enum: [...MSM_ACTIONS], required: true, description: 'Subcommand: list/exec/register/deregister/check/guide/catalog/ccc-config' },
    name: { type: 'string', description: 'MSM name (exec/register/deregister)' },
    args: { type: 'array', items: { type: 'string' }, description: 'exec business args (first arg --list/--schema <n>/--format=json is protocol flag, rest passed through losslessly)' },
    skill: { type: 'string', description: 'register owning skill' },
    path: { type: 'string', description: 'register script relative path (must be inside root and exist)' },
    category: { type: 'string', description: 'register category (mech/semi-mech)' },
    description: { type: 'string', description: 'register description' },
    flags: { type: 'string', description: 'register flags JSON string (new-style object array; type:"path" enables escape validation)' },
    usage: { type: 'string', description: 'register custom usage (auto-generated by default)' },
  },
  output: {
    schema: { type: 'json' },
    render: (args, value) => renderText(value),
  },
  async execute(args, exec) {
    const root = findSerenityRoot(agentCwd(exec))
    if (!root) throw new Error('No CCC found: no .serenity file from agent cwd')
    // F4b ⑨：Skiff 会话 MSM 白名单门控（exec 校验 / register-deregister 必拒 / list 过滤）
    const sessionId = agentSessionId(exec)
    const gate = skiffMsmGate(root, sessionId, args.action as string, args.name as string | undefined)
    if (gate.reject) throw new Error(gate.reject)
    if (args.action === 'list' && gate.whitelist) {
      const out = runMsm(root, args)
      const text = typeof out === 'string' ? out : JSON.stringify(out)
      const header = text.split('\n')[0] ?? ''
      const lines = text
        .split('\n')
        .slice(1)
        .filter((line) => {
          const name = line.split(' | ')[0]?.trim()
          return name !== undefined && name !== '' && gate.whitelist!.has(name)
        })
      return `${header}\n${lines.length > 0 ? lines.join('\n') : '(no MSM allowed in this role)'}`
    }
    // runMsmAsync：exec 用异步 execFile（不阻塞 web 事件循环，避免 MSM 自请求 3080 死锁）
    return runMsmAsync(root, args)
  },
})
